In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("demo_data.csv")

df.head()

,Transaction_ID,Date,Customer_Name,Age,Gender,City,Product_Category,Product_Name,Quantity,Unit_Price,Discount,Payment_Method,Rating
0,1001,2024-06-17,Tarek Farouk,51.0,Male,Alexandria,Books & Stationery,Data Science Book,4,480.06,0.05,Credit Card,2.0
1,1002,2024-04-16,Karim Zaki,49.0,Male,Luxor,Clothing,Jeans,4,664.29,0.15,Debit Card,1.0
2,1003,2024-09-30,Mariam Farouk,46.0,Female,Cairo,Home Appliances,Air Fryer,4,2671.02,0.05,Credit Card,3.0
3,1004,2024-07-04,Khaled Abdelrahman,21.0,Male,Mansoura,Furniture,Bookshelf,2,1302.73,0.15,InstaPay,4.0
4,1005,2024-03-01,Nour Sayed,19.0,Female,Cairo,Electronics,Laptop,5,12651.35,0.15,InstaPay,4.0

In [3]:
print(f"📊 Dataset Dimensions: {df.shape[0]} rows and {df.shape[1]} columns.")

df.info()

print(df.isnull().sum())

(133, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    133 non-null    int64
 1   Date              133 non-null    object
 2   Customer_Name     133 non-null    object
 3   Age               122 non-null    float64
 4   Gender            133 non-null    object
 5   City              133 non-null    object
 6   Product_Category  133 non-null    object
 7   Product_Name      133 non-null    object
 8   Quantity          133 non-null    int64
 9   Unit_Price        133 non-null    float64
 10  Discount          133 non-null    float64
 11  Payment_Method    128 non-null    object
 12  Rating            122 non-null    float64
dtypes: float64(4), int64(2), object(7)
memory usage: 13.6+ KB
Transaction_ID       0
Date                 0
Customer_Name        0
Age                 11
Gender               0
City                 0
Product_Category     0
Product_Name         0
Quantity             0
Unit_Price           0
Discount             0
Payment_Method       5
Rating              11
dtype: int64

In [4]:
(df.isnull().sum() / len(df) * 100).round(2)

Transaction_ID      0.00
Date                0.00
Customer_Name       0.00
Age                 8.27
Gender              0.00
City                0.00
Product_Category    0.00
Product_Name        0.00
Quantity            0.00
Unit_Price          0.00
Discount            0.00
Payment_Method      3.76
Rating              8.27
dtype: float64

In [6]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Age"].isnull().sum()

np.int64(0)

In [7]:
df["Payment_Method"].mode()[0]

'InstaPay'

In [12]:
df["Payment_Method"] = df["Payment_Method"].fillna(df["Payment_Method"].mode()[0])
df["Payment_Method"].isnull().sum()

np.int64(0)

In [13]:
df["Rating"] = df["Rating"].fillna(df["Rating"].median())
df["Rating"].isnull().sum()

np.int64(0)

In [14]:
(df.isnull().sum() / len(df) * 100).round(2)

Transaction_ID      0.0
Date                0.0
Customer_Name       0.0
Age                 0.0
Gender              0.0
City                0.0
Product_Category    0.0
Product_Name        0.0
Quantity            0.0
Unit_Price          0.0
Discount            0.0
Payment_Method      0.0
Rating              0.0
dtype: float64

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 130 entries, 0 to 129
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    130 non-null    int64
 1   Date              130 non-null    object
 2   Customer_Name     130 non-null    object
 3   Age               130 non-null    float64
 4   Gender            130 non-null    object
 5   City              130 non-null    object
 6   Product_Category  130 non-null    object
 7   Product_Name      130 non-null    object
 8   Quantity          130 non-null    int64
 9   Unit_Price        130 non-null    float64
 10  Discount          130 non-null    float64
 11  Payment_Method    130 non-null    object
 12  Rating            130 non-null    float64
dtypes: float64(4), int64(2), object(7)
memory usage: 14.2+ KB

In [18]:
df.describe()

,Transaction_ID,Age,Quantity,Unit_Price,Discount,Rating
count,130.000000,130.000000,130.000000,130.000000,130.000000,130.000000
mean,1065.500000,39.023077,3.523077,1719.840615,0.100769,2.869231
std,37.671829,11.861256,1.624499,2336.457780,0.068479,1.259928
min,1001.000000,19.000000,1.000000,78.660000,0.000000,1.000000
25%,1033.250000,30.000000,2.000000,454.772500,0.050000,2.000000
50%,1065.500000,39.000000,4.000000,966.120000,0.100000,3.000000
75%,1097.750000,47.750000,5.000000,1765.115000,0.150000,4.000000
max,1130.000000,60.000000,6.000000,13284.570000,0.200000,5.000000

In [19]:
df.dtypes

Transaction_ID        int64
Date                 object
Customer_Name        object
Age                 float64
Gender               object
City                 object
Product_Category     object
Product_Name         object
Quantity              int64
Unit_Price          float64
Discount            float64
Payment_Method       object
Rating              float64
dtype: object

In [20]:
df["Date"] = pd.to_datetime(df["Date"])
df.dtypes

Transaction_ID               int64
Date                datetime64[ns]
Customer_Name               object
Age                        float64
Gender                      object
City                        object
Product_Category            object
Product_Name                object
Quantity                     int64
Unit_Price                 float64
Discount                   float64
Payment_Method              object
Rating                     float64
dtype: object

In [21]:
for col in df.select_dtypes(include="object").columns:
    print(col, df[col].unique())

Customer_Name ['Tarek Farouk' 'Karim Zaki' 'Mariam Farouk' 'Khaled Abdelrahman'
 'Nour Sayed' 'Omar Sayed' 'Sara Ibrahim' '  Ahmed Mahmoud  '
 'Mona Khalil' 'Yasmin Hassan' 'Ali Hassan' 'Mohamed Ali'
 'Youssef Mostafa' 'Hoda Mahmoud' '  Amr Ibrahim  ' 'Ahmed Mahmoud'
 'Layla Nasser' 'Salma Zaki' '  Yasmin Hassan  ' '  Sara Ibrahim  '
 'Fatima Mostafa' 'Hassan Mansour' 'Rania Ali' '  Tarek Farouk  '
 '  Youssef Mostafa  ' 'Amr Ibrahim' '  Rania Ali  ' '  Ali Hassan  '
 '  Layla Nasser  ' '  Hassan Mansour  ' '  Nour Sayed  '
 '  Mariam Farouk  ' '  Mohamed Ali  ' '  Khaled Abdelrahman  '
 '  Hoda Mahmoud  ']
Gender ['Male' 'Female']
City ['Alexandria' 'Luxor' 'Cairo' 'Mansoura' 'Aswan' 'Giza' 'Tanta']
Product_Category ['Books & Stationery' 'Clothing' 'Home Appliances' 'Furniture'
 'Electronics']
Product_Name ['Data Science Book' 'Jeans' 'Air Fryer' 'Bookshelf' 'Laptop'
 'Office Chair' 'Notebook Set' 'Blender' 'Tablet' 'Coffee Maker' 'Desk'
 'Lamp' 'Hoodie' 'Microwave' 'Pen Set' 'Headphones' 'Smartwatch' 'Planner'
 'Sneakers' 'Jacket' 'T-Shirt' 'Smartphone']
Payment_Method ['Credit Card' 'Debit Card' 'InstaPay' 'Mobile Wallet' 'Cash']

In [22]:
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].str.strip()

In [23]:
df["Customer_Name"].unique()

array(['Tarek Farouk', 'Karim Zaki', 'Mariam Farouk',
       'Khaled Abdelrahman', 'Nour Sayed', 'Omar Sayed', 'Sara Ibrahim',
       'Ahmed Mahmoud', 'Mona Khalil', 'Yasmin Hassan', 'Ali Hassan',
       'Mohamed Ali', 'Youssef Mostafa', 'Hoda Mahmoud', 'Amr Ibrahim',
       'Layla Nasser', 'Salma Zaki', 'Fatima Mostafa', 'Hassan Mansour',
       'Rania Ali'], dtype=object)

In [24]:
df["Transaction_ID"].duplicated().sum()

np.int64(0)

In [26]:
df[(df["Age"] < 18) | (df["Age"] > 100)]

Empty DataFrame
Columns: [Transaction_ID, Date, Customer_Name, Age, Gender, City, Product_Category, Product_Name, Quantity, Unit_Price, Discount, Payment_Method, Rating]
Index: []

In [27]:
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Transaction_ID, Date, Customer_Name, Age, Gender, City, Product_Category, Product_Name, Quantity, Unit_Price, Discount, Payment_Method, Rating]
Index: []

In [28]:
df[(df["Rating"] < 1) | (df["Rating"] > 5)]

Empty DataFrame
Columns: [Transaction_ID, Date, Customer_Name, Age, Gender, City, Product_Category, Product_Name, Quantity, Unit_Price, Discount, Payment_Method, Rating]
Index: []

In [29]:
df[(df["Discount"] < 0) | (df["Discount"] > 1)]

Empty DataFrame
Columns: [Transaction_ID, Date, Customer_Name, Age, Gender, City, Product_Category, Product_Name, Quantity, Unit_Price, Discount, Payment_Method, Rating]
Index: []

In [30]:
df.isnull().sum()

Transaction_ID      0
Date                0
Customer_Name       0
Age                 0
Gender              0
City                0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount            0
Payment_Method      0
Rating              0
dtype: int64

In [ ]:
df.to_csv("cleaned_data.csv", index=False)